name: deploy to lambda
on: [push]
jobs:

  deploy:
    name: deploy lambda function
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '19'
    - name: Zip files
      uses: montudor/action-zip@v0.1.0
      with:
        args: zip -r output.zip src index.js package.json
    - name: AWS Lambda Deploy
      if: github.ref == 'refs/heads/master'
      uses: appleboy/lambda-action@v0.1.9
      with:
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws_region: ${{ secrets.AWS_REGION }}
        function_name: ${{ secrets.AWS_LAMBDA_NAME }}
        zip_file: output.zip
        dry_run: true
        runtime: nodejs18.x
        publish: true
        timeout: 10